// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4BSdQ0obM8w_tgMIDDDf8WtCDCnapUQ',
    appId: '1:1032054089420:web:5d61a8c211e9c240a10469',
    messagingSenderId: '1032054089420',
    projectId: 'najwa-firebase-b8834',
    authDomain: 'najwa-firebase-b8834.firebaseapp.com',
    storageBucket: 'najwa-firebase-b8834.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm00UwuqkJ9AASHYvZNDayN3Uwcs9cETM',
    appId: '1:1032054089420:android:b1530342b3d609c6a10469',
    messagingSenderId: '1032054089420',
    projectId: 'najwa-firebase-b8834',
    storageBucket: 'najwa-firebase-b8834.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyiHH0QXvTQVsyOFnC06d6p5ZXuZQG6s',
    appId: '1:1032054089420:ios:2f79dac1d9eeb84da10469',
    messagingSenderId: '1032054089420',
    projectId: 'najwa-firebase-b8834',
    storageBucket: 'najwa-firebase-b8834.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGyiHH0QXvTQVsyOFnC06d6p5ZXuZQG6s',
    appId: '1:1032054089420:ios:2f79dac1d9eeb84da10469',
    messagingSenderId: '1032054089420',
    projectId: 'najwa-firebase-b8834',
    storageBucket: 'najwa-firebase-b8834.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}